INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (1, NULL, NULL, 0, 1)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (2, NULL, NULL, 0, 1)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (3, NULL, NULL, 0, 1)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (4, NULL, NULL, 0, 1)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (5, NULL, NULL, 0, 1)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (6, NULL, NULL, 0, 1)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (7, NULL, NULL, 0, 1)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (8, NULL, NULL, 0, 1)

INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (9, NULL, NULL, 0, 2)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (10, NULL, NULL, 0, 2)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (11, NULL, NULL, 0, 2)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (12, NULL, NULL, 0, 2)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (13, NULL, NULL, 0, 2)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (14, NULL, NULL, 0, 2)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (15, NULL, NULL, 0, 2)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (16, NULL, NULL, 0, 2)

INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (17, NULL, NULL, 0, 3)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (18, NULL, NULL, 0, 3)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (19, NULL, NULL, 0, 3)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (20, NULL, NULL, 0, 3)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (21, NULL, NULL, 0, 3)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (22, NULL, NULL, 0, 3)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (23, NULL, NULL, 0, 3)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (24, NULL, NULL, 0, 3)

INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (25, NULL, NULL, 0, 4)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (26, NULL, NULL, 0, 4)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (27, NULL, NULL, 0, 4)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (28, NULL, NULL, 0, 4)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (29, NULL, NULL, 0, 4)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (30, NULL, NULL, 0, 4)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (31, NULL, NULL, 0, 4)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (32, NULL, NULL, 0, 4)

INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (33, NULL, NULL, 0, 5)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (34, NULL, NULL, 0, 5)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (35, NULL, NULL, 0, 5)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (36, NULL, NULL, 0, 5)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (37, NULL, NULL, 0, 5)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (38, NULL, NULL, 0, 5)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (39, NULL, NULL, 0, 5)
INSERT INTO [dbo].[Asientos] ([id], [tipo], [id_usuario], [estado], [fila]) VALUES (40, NULL, NULL, 0, 5)

